### ISSUE TITLE
Only characters are showing no word and sentence

### ISSUE THREAD

**Issue by rahurl** [luvk1412/Sign-Language-to-Text#28]
Only Character is showing no word and sentence part

**Comment by Goutham-1507** [comment]
hi bro..can u help me in installing hunspell package

**Comment by rahurl** [comment]
Run it on ubuntu no versions for windows

**Comment by Goutham-1507** [comment]
> Run it on ubuntu no versions for windows

kk. will try, thanks

**Comment by JosephineTina** [comment]
> > Run it on ubuntu no versions for windows
> 
> kk. will try, thanks

Sir did  you got it ... How should I install in ubuntu, it shows no module found (hunspell)
